export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
// HTMLの<head></head>に出力されるメタデータ（固定、全ページ共通）
// react-guide-material/21_nextjs_app_router/start/src/app/layout.jsなのでrootページで表示される

// HTMLを出力するための関数コンポーネント
// childrenにpage.jsの<ul></ul>が渡ってくる
// 全てのコンポーネントに適用されるレイアウトを指定する
// ファイル名はlayoutとする
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className="body-class">{children}</body>
    </html>
  )
}
